# Naive Baye's Algorithm

In [3]:
import numpy
import pandas
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [4]:
X,y=load_iris(return_X_y=True)

In [6]:
X.shape,y.shape

((150, 4), (150,))

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [ ]:
X_train

array([[5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 2.2, 5. , 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2.9, 3.6, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [6.1, 3. , 4.6, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [5.3, 3.7, 1.5, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [6.4, 2.7, 5.3, 1.9],
       [5.7, 3. , 4.2, 1.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.9, 3.1, 4.9, 1.5],
       [4.6, 3.1, 1.5, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5.1, 2.5, 3. , 1.1],
       [4.6, 3.4, 1.4, 0.3],
       [6.2, 2

In [9]:
from sklearn.naive_bayes import GaussianNB # Data contain the numerical continuous values

In [11]:
gnb=GaussianNB()

In [12]:
gnb.fit(X_train,y_train)

GaussianNB()

In [13]:
y_pred=gnb.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [16]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [17]:
import seaborn as sns
df=sns.load_dataset('tips')

In [18]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [34]:
X=df.iloc[:,:5]
y=df.iloc[:,5]
X,y

(     total_bill   tip     sex smoker   day
 0         16.99  1.01  Female     No   Sun
 1         10.34  1.66    Male     No   Sun
 2         21.01  3.50    Male     No   Sun
 3         23.68  3.31    Male     No   Sun
 4         24.59  3.61  Female     No   Sun
 ..          ...   ...     ...    ...   ...
 239       29.03  5.92    Male     No   Sat
 240       27.18  2.00  Female    Yes   Sat
 241       22.67  2.00    Male    Yes   Sat
 242       17.82  1.75    Male     No   Sat
 243       18.78  3.00  Female     No  Thur
 
 [244 rows x 5 columns],
 0      Dinner
 1      Dinner
 2      Dinner
 3      Dinner
 4      Dinner
         ...  
 239    Dinner
 240    Dinner
 241    Dinner
 242    Dinner
 243    Dinner
 Name: time, Length: 244, dtype: category
 Categories (2, object): ['Lunch', 'Dinner'])

In [19]:
df.day.value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [21]:
df.time.value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [22]:
df.sex.value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [23]:
df.smoker.value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [45]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [46]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [47]:
X_train

total_bill   tip     sex smoker   day
228       13.28  2.72    Male     No   Sat
208       24.27  2.03    Male    Yes   Sat
96        27.28  4.00    Male    Yes   Fri
167       31.71  4.50    Male     No   Sun
84        15.98  2.03    Male     No  Thur
..          ...   ...     ...    ...   ...
106       20.49  4.06    Male    Yes   Sat
14        14.83  3.02  Female     No   Sun
92         5.75  1.00  Female    Yes   Fri
179       34.63  3.55    Male    Yes   Sun
102       44.30  2.50  Female    Yes   Sat

[195 rows x 5 columns]

In [48]:
y_test

24     Dinner
6      Dinner
153    Dinner
211    Dinner
198     Lunch
176    Dinner
192     Lunch
124     Lunch
9      Dinner
101    Dinner
45     Dinner
233    Dinner
117     Lunch
177    Dinner
82      Lunch
146     Lunch
200     Lunch
15     Dinner
66     Dinner
142     Lunch
33     Dinner
19     Dinner
109    Dinner
30     Dinner
186    Dinner
120     Lunch
10     Dinner
73     Dinner
159    Dinner
156    Dinner
112    Dinner
218    Dinner
25     Dinner
60     Dinner
18     Dinner
119     Lunch
97     Dinner
197     Lunch
139     Lunch
241    Dinner
75     Dinner
127     Lunch
113    Dinner
16     Dinner
196     Lunch
67     Dinner
168    Dinner
38     Dinner
195     Lunch
Name: time, dtype: category
Categories (2, object): ['Lunch', 'Dinner']

In [49]:
dayle=LabelEncoder()
X_train["day"]=dayle.fit_transform(X_train["day"])
X_test["day"]=dayle.transform(X_test["day"])

In [50]:
from sklearn.compose import ColumnTransformer
categorical=['sex','smoker']
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(drop='first'), categorical)], remainder='passthrough')
X_train=ct.fit_transform(X_train)
X_test=ct.transform(X_test)

In [52]:
y_train=y_train.replace({"Lunch":0,"Dinner":1})
y_test=y_test.replace({"Lunch":0,"Dinner":1})

C:\Users\Thoyajaksha Kashyap\AppData\Local\Temp\ipykernel_35648\2476190537.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y_train=y_train.replace({"Lunch":0,"Dinner":1})
C:\Users\Thoyajaksha Kashyap\AppData\Local\Temp\ipykernel_35648\2476190537.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  y_train=y_train.replace({"Lunch":0,"Dinner":1})
C:\Users\Thoyajaksha Kashyap\AppData\Local\Temp\ipykernel_35648\2476190537.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old 

In [54]:
y_train.shape

(195,)

In [55]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train,y_train)
y_pred=gnb.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9183673469387755
[[13  2]
 [ 2 32]]
              precision    recall  f1-score   support

           0       0.87      0.87      0.87        15
           1       0.94      0.94      0.94        34

    accuracy                           0.92        49
   macro avg       0.90      0.90      0.90        49
weighted avg       0.92      0.92      0.92        49

