In [4]:
import numpy as np

## Create array using numpy
## create a 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [8]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
## 2d array
arr2 = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes of numpy
arr = np.array([[1,2,3],[4,5,6]])
print("Array: \n", arr)
print("Shape: ", arr.shape)
print("Number of dimensions: ", arr.ndim)
print("Size (number of elements): ", arr.size)
print("Data type: ", arr.dtype)
print("Item size (in bytes): ", arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size (number of elements):  6
Data type:  int32
Item size (in bytes):  4


In [16]:
## Numpy Vectorized Operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
# Element wise addition
print("Addition: ", arr1 + arr2)
# Element wise subtraction
print("Subtraction: ", arr1 - arr2)
# Element wise multiplication
print("Multiplication: ", arr1 * arr2)
# Element wise division
print("Division: ", arr1 / arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [18]:
## Universal functions
arr = np.array([2,3,4,5,6])
# square root
print(np.sqrt(arr))
# Exponential
print(np.exp(arr))
# natural log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [19]:
## array slicing and indexing

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
print(arr[0][1])
print(arr[0:2, 2:])
print(arr[1:, 1:3])

2
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [23]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [28]:
## Modify array elements
arr[0,0] = 100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [30]:
arr[1:]= 100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [31]:
### statistical concepts - Normalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

# Calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalized the data

normalized_data = (data-mean)/std_dev
print("Normalized data: ", normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [32]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
print("Mean: ", np.mean(data))
print("Median: ", np.median(data))
print("Standard Deviation: ", np.std(data))
print("Variance: ", np.var(data))

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [37]:
## Logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>5) & (data<8)]

array([6, 7])